services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: docker.io/richardluo831/ramulator2
    init: true
    working_dir: /home/dev
    volumes:
    - .:/home/dev
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    network_mode: host
